#pragma once

#include <string>

namespace {{NAMESPACE}} {

/**
 * @brief Main class for {{PROJECT_NAME}}.
 * Generated by Cmake_Module_Create_Tool.
 */
class {{PROJECT_NAME}} {
public:
    {{PROJECT_NAME}}();
    virtual ~{{PROJECT_NAME}}();

    /**
     * @brief Performs a sample operation on an input.
     * @param input A sample input value.
     * @return The result of the operation.
     */
    int performOperation(int input);

    /**
     * @brief Gets a welcome message.
     * @return A string containing the welcome message.
     */
    std::string getWelcomeMessage() const;
};

} // namespace {{NAMESPACE}}
